### ISSUE TITLE
Dodać zarządzanie zależnościami przez browserify

### ISSUE THREAD

**Issue by pdorofiejczyk** [awojsznis/TODOS-mvc#1]
1. Zainicjuj paczkę npm w swoim repozytorium
`npm init`
2. Dodaj zależność browserify
`npm install browserify --save-dev`
3. Dodaj do TodoModel eksporty
`module.exports = TodoModel`
4. Dodaj do test.js zależność od modułu TodoModel
`var TodoModel = require('./TodoModel');`
5. Spróbuj "skompilować"
`browserify test.js -o dist/test.js`
6. W index.html linkuj tylko do dist/test.js
7. Sprawdź czy testy odpalają się jak przed modyfikacjami
8. Dodaj w package.json skrypt build w sekcji "scripts" (https://docs.npmjs.com/misc/scripts) tak aby była wywoływana komenda z p.5

**Comment by awojsznis** [comment]
Zriobione.

**Comment by pdorofiejczyk** [comment]
ok
