### ISSUE TITLE
Dodać inkrementalne identyfikatory dla elementów todo

### ISSUE THREAD

**Issue by pdorofiejczyk** [awojsznis/TODOS-mvc#2]
Obecnie bazujemy na kluczach tablicy co jest problematyczne ponieważ zmieniają się one przy modyfikacjach tablicy (w szczególności po wywołaniu clearCompleted). Może to później prowadzić do błędów jeśli gdzieś mamy zapamiętane stare identyfikatory i po nich się odwołujemy. Kod jest także gorzej testowalny (patrz moje komentarze do test.js).

Trzeba dodawać pole id do każdego elementu todo. Powinien być to inkrementalny id. Licznik trzymajmy w zmiennej prywatnej w modelu TodoModel.

**Comment by awojsznis** [comment]
Czyli metody markAsCompleted i markAsActive przepisać tak żeby zamiast parametru index przyjmowały id?

**Comment by pdorofiejczyk** [comment]
Tak, dokładnie

**Comment by awojsznis** [comment]
Zrobione
