### ISSUE TITLE
Observable zaciągane z npm

### ISSUE THREAD

**Issue by pdorofiejczyk** [awojsznis/TODOS-mvc#3]
Po zakończeniu zadania https://github.com/awojsznis/TODOS-mvc/issues/1 możemy dodać zależność observable tak żeby zaciągała się z npm (dzięki temu nie musimy trzymać jej w repo).
https://www.npmjs.com/package/riot-observable

**Comment by awojsznis** [comment]
Zrobione.

**Comment by pdorofiejczyk** [comment]
ok
