### ISSUE TITLE
Przepisać testy na QUnit

### ISSUE THREAD

**Issue by pdorofiejczyk** [awojsznis/TODOS-mvc#5]
1. Dodać zależnośc dev od https://qunitjs.com wg. "Getting started" (plik html zapisać jako test.html)
2. Przepisać test.js wg dokumentacji QUnit
3. Sprawdzić czy po odpaleniu test.html testy odpalają się w przeglądarce
4. Dodać zależność dev od https://github.com/jonkemp/node-qunit-phantomjs
5. Spróbować odpalić ten sam test.html z konsoli za pomocą node-qunit-phantomjs
6. Dodać skrypt npm w package.json o nazwie "test" odpalający node-qunit-phantomjs

**Comment by awojsznis** [comment]
Zrobione.
